### ISSUE TITLE
Jupyter notebook relative paths not resolving correctly

### ISSUE THREAD

**Issue by isabelleaugenstein** [copenlu/stat-nlp-book#4]
Since updating the requirements, the relative notebook links from e.g. `https://github.com/copenlu/stat-nlp-book/blob/master/overview.ipynb` don't resolve properly anymore when viewing the static version on Github. @danielhers @apepa, do you know why or how to solve this? Probably best to revert to the older version if not.

**Comment by danielhers** [comment]
Related to jupyter/jupyter-book#232

**Comment by danielhers** [comment]
Are you sure it's related to the requirements?
Strangely, when I click the link normally it _does_ work, but when I "open in a new tab" it doesn't!

**Comment by isabelleaugenstein** [comment]
Yeah, same here -- new tab is what I do by default. This used to work, and the only significant thing that has changed are the requirements.

**Comment by isabelleaugenstein** [comment]
@danielhers, could you change it back? That doesn't seem to resolve things. Maybe we can just add a note saying that opening in a new tab currently doesn't work.
Maybe it's also related to a change Github has made.

**Comment by danielhers** [comment]
Sure.

**Comment by danielhers** [comment]
I think the solution should just be to use the Jupyter Notebook Viewer instead of trying to view the notebooks directly on GitHub, since the GitHub viewer seems buggy: https://nbviewer.jupyter.org/github/copenlu/stat-nlp-book/blob/master/overview.ipynb

Any notebook can be viewed there by pasting its URL in https://nbviewer.jupyter.org/, for example, https://nbviewer.jupyter.org/github/COPENLU/STAT-NLP-BOOK/tree/master/

**Comment by isabelleaugenstein** [comment]
Yeah, let's keep it as is. We need relative paths for viewing notebooks
locally. Thanks a lot for looking into this though.
